/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QKART_SANITY_LOGIN;

import org.openqa.selenium.chrome.ChromeDriver;



public class QkartSanity {

    public static String lastGeneratedUserName;
    public static ChromeDriver createDriver() {
        ChromeDriver driver;
        //IMPORTANT!: Enter the Driver Location here 
        String driverLocation = "/Users/praveenkumar/Documents/CrioDo/Java_Workspace_Grouping/Module1_2TCs_Standardization/app/chromedriver";//IMPORTANT!: Enter the Driver Location here 
        System.setProperty("webdriver.chrome.driver", driverLocation);
        driver = new ChromeDriver();
        return driver;
    }

    public static void logStatus(String type, String message, String status) 
    {
        
        System.out.println(String.format("%s |  %s  |  %s | %s", String.valueOf(java.time.LocalDateTime.now()) , type , message , status));

    }

    public static Boolean TestCase01(ChromeDriver driver) throws InterruptedException {
        Boolean status;
        logStatus("Start TestCase", "Test Case 1: Verify User Registration", "DONE");
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("TestCase 1", "Test Case Failure. User Registration Failed", "FAIL");
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;
        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        Home home = new Home(driver);
        status = home.PerformLogout();
        logStatus("End TestCase", "Test Case 1: Verify user Regsitration : ", status? "PASS":"FAIL");
        return status;
    }

    public static Boolean TestCase02(ChromeDriver driver) throws InterruptedException {
        Boolean status;
        String TestStatus = "";
        logStatus("Start Testcase", "Test Case 2: Verify User Registration with an existing username ", "DONE");
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser(lastGeneratedUserName, "abc@123", false);
        if (!status) {
            TestStatus = "PASS";

        } else {
            TestStatus = "FAIL";
        }
        logStatus("End Testcase", "Test Case 2: Verify user Re-Regsitration", TestStatus);
        return !status;
    }

    public static void main(String[] args) throws InterruptedException {
        ChromeDriver driver = createDriver();

        // Executing Test Case 1
        TestCase01(driver);

        // Executing Test Case 2
        TestCase02(driver);

        // quit Chrome Driver
        driver.quit();
    }
}
