/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QKART_SANITY_LOGIN;

import org.openqa.selenium.chrome.ChromeDriver;



public class QkartSanity {

    public static String lastGeneratedUserName;
    public static ChromeDriver createDriver() {
        ChromeDriver driver;
        // TODO: CRIO_TASK_MODULE_DEBUGGING: IMPORTANT! Enter the Driver Location here
        String driverLocation = "/Users/praveenkumar/Documents/CrioDo/Java_Workspace_Grouping/Module1_2TCs_Standardization/app/chromedriver";//IMPORTANT!: Enter the Driver Location here 
        System.setProperty("webdriver.chrome.driver", driverLocation);
        driver = new ChromeDriver();
        return driver;
    }

    public static void logStatus(String type, String message, String status) 
    {
        
        System.out.println(String.format("%s |  %s  |  %s | %s", String.valueOf(java.time.LocalDateTime.now()) , type , message , status));

    }

    public static Boolean TestCase01(ChromeDriver driver) throws InterruptedException {
        Boolean status;
        logStatus("Start TestCase", "Test Case 1: Verify Functionality of Login button on home page ", "DONE");
        Home homePage = new Home(driver);
        homePage.navigateToHome();
        Thread.sleep(2000);
        status = homePage.VerifyLoginButton();
        logStatus("Step", "Test Case 1: Verify Login Button Exists : ", status? "PASS":"FAIL");
        status = homePage.clickLoginButton();
        status = driver.getCurrentUrl().endsWith("/login");
        logStatus("Step", "Test Case 1: Verify that user navigates to login page when login button is clicked : ", status? "PASS":"FAIL");
        logStatus("End TestCase", "Test Case 1:Verify Functionality of Login button on home page  : ", status? "PASS":"FAIL");
        return status;
    }

    public static Boolean TestCase02(ChromeDriver driver) throws InterruptedException {
        Boolean status;
        logStatus("Start TestCase", "Test Case 2: Verify Functionality of Register button on home page ", "DONE");
        Home homePage = new Home(driver);
        homePage.navigateToHome();
        Thread.sleep(2000);
        status = homePage.VerifyRegisterButton();
        logStatus("Step", "Test Case 1: Verify Register Button Exists : ", status? "PASS":"FAIL");
        status = homePage.clickRegisterButton();
        status = driver.getCurrentUrl().endsWith("/register");
        logStatus("Step", "Test Case 1: Verify that user navigates to registration page when Register button is clicked : ", status? "PASS":"FAIL");
        logStatus("End TestCase", "Test Case 1:Verify Functionality of Register button on home page  : ", status? "PASS":"FAIL");
        return status;
    }

    public static void main(String[] args) throws InterruptedException {
        ChromeDriver driver = createDriver();

        // Executing Test Case 1
        TestCase01(driver);

        // Executing Test Case 2
        TestCase02(driver);

        // quit Chrome Driver
        driver.quit();
    }
}
