/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QKART_SANITY_LOGIN;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.BrowserType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

public class QkartSanity {

    public static String lastGeneratedUserName;

    public static RemoteWebDriver createDriver() throws MalformedURLException {
        // Launch Browser using Zalenium
        final DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setBrowserName(BrowserType.CHROME);
        RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:8082/wd/hub"), capabilities);

        // Maximize and Implicit Wait for things to initailize
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

        return driver;
    }

    public static void logStatus(String type, String message, String status) {

        System.out.println(String.format("%s |  %s  |  %s | %s", String.valueOf(java.time.LocalDateTime.now()), type,
                message, status));

    }

    public static Boolean TestCase01(RemoteWebDriver driver) throws InterruptedException {
        Boolean status;
        logStatus("Start TestCase", "Test Case 1: Verify Functionality of Login button on home page ", "DONE");
        Home homePage = new Home(driver);
        homePage.navigateToHome();
        Thread.sleep(2000);
        status = homePage.VerifyLoginButton();
        logStatus("Step", "Test Case 1: Verify Login Button Exists : ", status ? "PASS" : "FAIL");
        status = homePage.clickLoginButton();
        status = driver.getCurrentUrl().endsWith("/login");
        logStatus("Step", "Test Case 1: Verify that user navigates to login page when login button is clicked : ",
                status ? "PASS" : "FAIL");
        logStatus("End TestCase", "Test Case 1:Verify Functionality of Login button on home page  : ",
                status ? "PASS" : "FAIL");
        return status;
    }

    public static Boolean TestCase02(RemoteWebDriver driver) throws InterruptedException {
        Boolean status;
        logStatus("Start TestCase", "Test Case 2: Verify Functionality of Register button on home page ", "DONE");
        Home homePage = new Home(driver);
        homePage.navigateToHome();
        Thread.sleep(2000);
        status = homePage.VerifyRegisterButton();
        logStatus("Step", "Test Case 1: Verify Register Button Exists : ", status ? "PASS" : "FAIL");
        status = homePage.clickRegisterButton();
        status = driver.getCurrentUrl().endsWith("/register");
        logStatus("Step",
                "Test Case 1: Verify that user navigates to registration page when Register button is clicked : ",
                status ? "PASS" : "FAIL");
        logStatus("End TestCase", "Test Case 1:Verify Functionality of Register button on home page  : ",
                status ? "PASS" : "FAIL");
        return status;
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        RemoteWebDriver driver = createDriver();

        // Executing Test Case 1
        TestCase01(driver);

        // Executing Test Case 2
        TestCase02(driver);

        // quit Chrome Driver
        driver.quit();
    }
}
